inheritedBy:
  tags:
    - repository
tasks:
  bundle-optional:
    description: Install the optional Brewfile
    deps:
      - repository:homebrew
    checks:
      - check: condition
        script: |-
          export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
          export HOMEBREW_DOTFILES_SKIP_PAID_APPS="${SKIP_PAID_APPS:-0}"
          brew bundle check --quiet --no-upgrade --file Brewfile.optional
    env:
      HOMEBREW_NO_ASK: "1"
      HOMEBREW_BUNDLE_MAS_SKIP: ""
    inputs:
      - Brewfile.optional
    toolchains: system
    options:
      cache: false
      mutex: homebrew
      os: macos
      runInCI: false
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      export HOMEBREW_DOTFILES_SKIP_PAID_APPS="${SKIP_PAID_APPS:-0}"
      brew bundle install --no-upgrade --file Brewfile.optional </dev/null
