inheritedBy:
  tags:
    - rust-cli
fileGroups:
  rust:
    - Cargo.toml
    - Cargo.lock
    - build*.rs
    - src/**/*
    - tests/**/*
    - examples/**/*
    - benches/**/*
    - /.cargo/**/*
    - /clippy.toml
    - /rustfmt.toml
    - /LICENSE
    - /tooling/RUST.md
tasks:
  fmt:
    deps:
      - repository:rust
    checks:
      - |-
        export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
        cargo fmt --version
    inputs:
      - "@group(rust)"
    toolchains: system
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo fmt --all --check
  clippy:
    deps:
      - repository:rust
    checks:
      - |-
        export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
        cargo clippy --version
    inputs:
      - "@group(rust)"
    toolchains: system
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
  check:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: system
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo check --workspace --all-targets --all-features --locked
  doc:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: system
    env:
      RUSTDOCFLAGS: -Dwarnings
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo doc --workspace --all-features --no-deps --locked
  test:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: system
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo test --workspace --all-features --locked
