inheritedBy:
  tags:
    - rust-cli
fileGroups:
  rust:
    - Cargo.toml
    - Cargo.lock
    - moon.yml
    - .cargo/**/*
    - "{clippy,.clippy}.toml"
    - "{rustfmt,.rustfmt}.toml"
    - "{rust-toolchain,rust-toolchain.toml}"
    - build*.rs
    - src/**/*
    - tests/**/*
    - examples/**/*
    - benches/**/*
    - /.cargo/**/*
    - "/{clippy,.clippy}.toml"
    - "/{rustfmt,.rustfmt}.toml"
    - "/{rust-toolchain,rust-toolchain.toml}"
    - /.moon/toolchains.yml
    - /.moon/tasks/workstation.yml
    - /.prototools
    - /moon.yml
    - /LICENSE
    - /tooling/RUST.md
tasks:
  fmt:
    deps:
      - repository:rust
    checks:
      - |-
        export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
        cargo fmt --version
    inputs:
      - "@group(rust)"
    toolchains: rust
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo fmt --all --check
  clippy:
    deps:
      - repository:rust
    checks:
      - |-
        export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
        cargo clippy --version
    inputs:
      - "@group(rust)"
    toolchains: rust
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
  check:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: rust
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo check --workspace --all-targets --all-features --locked
  doc:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: rust
    env:
      RUSTDOCFLAGS: -Dwarnings
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo doc --workspace --all-features --no-deps --locked
  test:
    deps:
      - repository:rust
    inputs:
      - "@group(rust)"
    toolchains: rust
    script: |-
      export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"
      cargo test --workspace --all-features --locked
