#!/usr/bin/env bash

function git_hook_detect_copy_paste () {
  echo 'Check for copy paste'
  start=$(git_main_branch)
  git diff origin/${start}... \
    --name-only \
    --relative \
    --diff-filter=d \
    -- ':!.yarn*' \
    | grep -v '__fixtures__' \
    | grep -v '__FIXTURES__' \
    | grep -v '__snapshots__' \
    | grep -v '.test.' \
    | xargs jscpd --reporters consoleFull
}
