#!/usr/bin/env bash

INSTANCE_NAME="Import Server"

# Retrieve instance Id
INSTANCE_ID=$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=$INSTANCE_NAME" \
    --query "Reservations[].Instances[?State.Name=='stopped'].InstanceId" \
    --output text)

if [ -z "$INSTANCE_ID" ]; then
    echo "No instance stopped with name $INSTANCE_NAME."
    exit 1
fi

aws ec2 start-instances --instance-ids $INSTANCE_ID

echo "Instance $INSTANCE_NAME ($INSTANCE_ID) is starting..."
