#!/bin/bash

echo "ℹ️  Brew"
brew update
brew upgrade
brew upgrade --cask
brew cleanup -s

echo "ℹ️  Brew diagnostic"
brew doctor
brew missing

echo "ℹ️  Mas upgrade"
mas outdated
mas upgrade

echo "ℹ️  Npm upgrade"
npm-check -g -y
