# Repo
# antigen use oh-my-zsh

# Bundles
# antigen bundle git
# antigen bundle zsh-users/zsh-syntax-highlighting
# antigen bundle robbyrussell/oh-my-zsh plugins/docker-compose/docker-compose.plugin.zsh
# antigen bundle sparsick/ansible-zsh
# antigen bundle webyneter/docker-aliases.git
# antigen bundle laurenkt/zsh-vimto
# antigen bundle zsh-users/zsh-autosuggestions
# antigen bundle wfxr/forgit
# antigen bundle sharat87/zsh-vim-mode



# Theme
# antigen theme subnixr/minimal
# antigen bundle sindresorhus/pure

# antigen apply

# zstyle ':completion:*:*:docker:*' option-stacking yes
# zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Alias
# source ~/.dotfiles/zsh/alias

# Homebrew
[[ -d /opt/homebrew/bin ]] && export PATH=$PATH:/opt/homebrew/bin

# Starship
eval "$(starship init zsh)"

# Volta
[[ -d $HOME/.volta ]] && export PATH=$HOME/.volta/bin:$PATH

# Setup default editor
[[ ! -z `command -v nvim` ]] && export EDITOR=nvim

# Auto suggestion
[[ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
# Syntax
[[ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -d ~/.zsh/zsh-completions ]] && fpath=(~/.zsh/zsh-completions $fpath)
