#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
bootstrap_directory="$(mktemp -d)"
trap 'rm -r "$bootstrap_directory"' EXIT
export PROTO_HOME="$bootstrap_directory/proto"
export PROTO_CLI_UNMANAGED_INSTALL="$PROTO_HOME/bin"
export PROTO_AUTO_INSTALL=true
export PROTO_DETECT_STRATEGY=only-prototools
unset PROTO_MOON_VERSION PROTO_ENV

proto_installer="$(curl -fsSL --connect-timeout 10 --max-time 60 https://github.com/moonrepo/proto/releases/latest/download/proto_cli-installer.sh)"
/bin/sh -c "$proto_installer"
"$PROTO_HOME/bin/proto" --config-mode local run moon -- --version
moon_binary="$("$PROTO_HOME/bin/proto" --config-mode local bin moon)"
mkdir -p "$HOME/.moon/bin"
install -m 755 "$moon_binary" "$HOME/.moon/bin/moon"
"$HOME/.moon/bin/moon" --version
