name: Static gates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static:
    name: Static gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095
      - run: >-
          moon ci repository:typescript-lint repository:typescript-typecheck
          repository:typescript-format-check repository:prettier-check
