name: Arnes tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  arnes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: moonrepo/setup-toolchain@v0
      - run: >-
          moon ci tooling/arnes:fmt tooling/arnes:clippy
          tooling/arnes:check tooling/arnes:test
