name: Rust tests

on:
  push:
    paths:
      - daily-routine/**
      - .github/workflows/test-rust.yml
  pull_request:
    paths:
      - daily-routine/**
      - .github/workflows/test-rust.yml

jobs:
  daily-routine:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --manifest-path daily-routine/Cargo.toml --check
      - run: cargo clippy --manifest-path daily-routine/Cargo.toml -- -D warnings
      - run: cargo test --manifest-path daily-routine/Cargo.toml
