name: Deployment tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deployment:
    name: Deployment (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095
      - run:
          moon ci --concurrency 1 --downstream none tooling:deployment-test tooling:hunspell-test
          tooling:apple-notes-test tooling:pr-feedback-skill-test
